const assertArraysEqual = require('../assertArraysEqual');
const eqArrays = require('../eqArray');
const middle = require('../middle');
assertArraysEqual(middle([1, 2, 3]), [2]);
assertArraysEqual(middle([1, 2, 3, 4, 5]), [3]);
assertArraysEqual(middle([2, 3, 4, 7, 1, 6, 8]), [7]);
assertArraysEqual(middle([1, 2, 3, 4, 5, 6]), [3, 4]);
assertArraysEqual(middle([1, 2, 3, 4]), [2, 4]);
assertArraysEqual(middle([]), []);
assertArraysEqual(middle([1, 2]), []);